### ISSUE TITLE
Не работают несколько функций

### ISSUE THREAD

**Issue by TikhonM** [oncecreated/cleverapi#10]
Здравствуйте, не сработали следующие функции:

1) api.send_action(action_id=Action.JOIN_GAME, user_id=lp.user_id

Traceback (most recent call last): 
File "...", line 398, in start_game 
api.send_action(action_id=Action.JOIN_GAME, user_id=lp.user_id) 
File "...", line 62, in send_action 
return self.fetch("streamQuiz.trackAction", data) 
File "...", line 137, in fetch 
raise ApiResponseError(json.dumps(content)) 
cleverapi.exceptions.ApiResponseError: {"error": {"error_code": 8, "error_msg": "Invalid request: bad action_id", "request_params": [{"key": "oauth", "value": "1"}, {"key": "method", "value": "streamQuiz.trackAction"}, {"key": "action_id", "value": "2"}, {"key": "hash", "value": "..."}, {"key": "v", "value": "5.73"}, {"key": "lang", "value": "ru"}, {"key": "https", "value": "1"}]}} 

2) api.comment(owner_id=lp.owner_id, video_id=lp.video_id, message='Тест')

 print(api.comment(owner_id=lp.owner_id, video_id=lp.video_id, message='Тест')) выводит 0, а сообщение не отправляется

3) api.use_extra_life()

Может, в эту функцию нужно что-то передать? У меня выскакивает ошибка:

Traceback (most recent call last): 
File "...", line 917, in _bootstrap_inner 
self.run() 
File "...", line 556, in run 
lp.game_waiting() 
File "...", line 72, in game_waiting 
self.__start_polling(game) 
File "...", line 97, in __start_polling 
self.event_loop() 
File "...", line 106, in event_loop 
self.process_event(event) 
File "...", line 122, in process_event 
self.notify_hadlers(event, self.handlers[event_type]) 
File "...", line 144, in notify_hadlers 
handler(event) 
File "...", line 463, in give_actions 
print(api.use_extra_life()) 
File "...", line 93, in use_extra_life 
return self.fetch("streamQuiz.useExtraLife") 
File "...", line 137, in fetch 
raise ApiResponseError(json.dumps(content)) 
cleverapi.exceptions.ApiResponseError: {"error": {"error_code": 10, "error_msg": "Internal server error", "request_params": [{"key": "oauth", "value": "1"}, {"key": "method", "value": "streamQuiz.useExtraLife"}, {"key": "v", "value": "5.73"}, {"key": "lang", "value": "ru"}, {"key": "https", "value": "1"}]}}

Что не так я делаю? Подскажите, пожалуйста. Если не сложно, приведите примеры.

Заранее спасибо)))

**Comment by ilyaeyoza** [comment]
video и owner id достается так:
data = api.get_start_data()
print(data) 
Ну а потом вытащи что надо.
