### ISSUE TITLE
Действие "Вы присоединились к игре"

### ISSUE THREAD

**Issue by Takolp** [oncecreated/cleverapi#12]
При вызова действия "Вы присоединились к игре" получаю такую ошибку: {"error": {"error_code": 8, "error_msg": "Invalid request: bad action_id", "request_params": [{"key": "oauth", "value": "1"}, {"key": "method", "value": "streamQuiz.trackAction"}, {"key": "action_id", "value": "2"}, {"key": "hash", "value": ""}, {"key": "v", "value": "5.73"}, {"key": "lang", "value": "ru"}, {"key": "https", "value": "1"}]}}

**Comment by geosonic** [comment]
Подробно описано

**Comment by Sc-Ximik** [comment]
Действие "Вы присоединились к игре" убрали. За это отвечает теперь другой метод

**Comment by Takolp** [comment]
> Действие "Вы присоединились к игре" убрали. За это отвечает теперь другой метод

Какой?

**Comment by Sc-Ximik** [comment]
> > Действие "Вы присоединились к игре" убрали. За это отвечает теперь другой метод
> 
> Какой?

execute.liveHeartbeat
