### ISSUE TITLE
Функционал для Клевер Боя

### ISSUE THREAD

**Issue by akudryav** [oncecreated/cleverapi#13]
Есть в этой библиотеке Функционал для Клевер Боя? то есть игры один на один со случайным соперником?

**Comment by geosonic** [comment]
Нет.

**Comment by Sc-Ximik** [comment]
В чем проблема написать самому?

**Comment by akudryav** [comment]
> В чем проблема написать самому?

А где взять описание происходящих при этом событий? разве есть техническая дока по клеверу?

**Comment by oncecreated** [comment]
@akudryav вы можете прослушать трафик официального приложения, это единственный источник информации. Функционал клевер боя появится в следующем обновлении библиотеки.

**Comment by Sc-Ximik** [comment]
> > В чем проблема написать самому?
> 
> А где взять описание происходящих при этом событий? разве есть техническая дока по клеверу?

Декомпилируй апк клевера и найди нужные методы
