### ISSUE TITLE
Кто поможет создать бота, который смог бы играть за несколько аккаунтов?

### ISSUE THREAD

**Issue by dan0102dan** [oncecreated/cleverapi#15]

**Comment by Sc-Ximik** [comment]
Берешь, засовываешь токены в массив, потом циклом for прогоняешь каждый из них, профит...

**Comment by dan0102dan** [comment]
Можете помочь?

**Comment by dan0102dan** [comment]
Буду благодарен

**Comment by dan0102dan** [comment]
Пришли, пожалуйста, ссылку на себя в вк

**Comment by Sc-Ximik** [comment]
> Можете помочь?

array = [тут токены через запятую]

for i in range(количество токенов):
потом в нужном месте вписываешь array[i]

**Comment by dan0102dan** [comment]
Пришлите ссылку на вк
