### ISSUE TITLE
Ошибка документации

### ISSUE THREAD

**Issue by LowderPlay** [oncecreated/cleverapi#5]
В документации событий, в событии `sq_question_answers_right` допущена ошибка. Нет параметра отвечающего за номер ответа пользователя. Исправьте документацию или меня. UPD: Мой косяк, параметр не передаётся, но как приложение отмечает ответ пользователя в ответе?

**Comment by oncecreated** [comment]
Клевер никак не отмечает ответ пользователя в событии `sq_question_answers_right`. Нужно отдельно запоминать ответ пользователя, если это возможно.

**Comment by katant** [comment]
Клевер хранит верный ответ прямо в переменной, проще говоря если выйти из приложения, оно не запомнит ваш ответ

**Comment by LowderPlay** [comment]
Тогда спасибо. Возможно клевер не увидел количество ответивших, поэтому выбил меня из игры. Я просто делаю эмулятор сервера.
